import { faEdit, faTrashCan, faSquare, faBell, faUserCircle } from '@fortawesome/free-regular-svg-icons';
import {
  faAddressBook,
  faAt,
  faCalendar,
  faLocationDot,
  faLock,
  faPenClip,
  faPhone,
  faShare,
  faSpa,
  faSpinner,
  faUser,
  faVenusMars,
  faCheckSquare,
  faRightFromBracket,
  faArrowLeft,
  faAngleDown,
  faAngleUp,
  faCheck,
  faX,
  faBan,
  faExclamationCircle,
  faPerson,
  faPersonDress,
  faCheckCircle,
  faPlus,
  faSearch,
  faCalendarAlt,
  faCommentDots,
  faHandshake,
  faWifi,
} from '@fortawesome/free-solid-svg-icons';

const icons = {
  spinner: faSpinner,
  user: faUser,
  username: faAddressBook,
  password: faLock,
  phone: faPhone,
  email: faAt,
  date: faCalendar,
  source: faShare,
  assign: faPenClip,
  age: faSpa,
  gender: faVenusMars,
  male: faPerson,
  female: faPersonDress,
  city: faLocationDot,
  edit: faEdit,
  trash: faTrashCan,
  logout: faRightFromBracket,
  back: faArrowLeft,
  angleUp: faAngleUp,
  angleDown: faAngleDown,
  search: faSearch,
  plus: faPlus,
  square: faSquare,
  checkSquare: faCheckSquare,
  checkCircle: faCheckCircle,
  check: faCheck,
  x: faX,
  ban: faBan,
  exclamationCircle: faExclamationCircle,
  wifi: faWifi,
  notifications: faBell,
  profile: faUserCircle,
  actions: {
    call: faPhone,
    message: faCommentDots,
    meeting: faCalendarAlt,
    deal: faHandshake,
  },
};

export default icons;
